version: '3.8'

services:
  tailscale:
    image: tailscale/tailscale
    network_mode: "host"
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-exit-node
      - TS_ROUTES=192.168.86.0/24
    volumes:
      - tailscale-data1:/var/lib 
      - tailscale-data2:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
    
volumes:
  tailscale-data1:
    external: true
  tailscale-data2:
    external: true
