services:
  filebot:
    image: jlesage/filebot
    container_name: filebot
    restart: unless-stopped
    environment:
      - USER_ID=1001
      - GROUP_ID=1001
    ports:
      - 5800:5800
    volumes:
      - /docker/appdata/filebot:/config:rw
      - /home_theater_data/torrents/completed:/storage:rw
