services:
  uptimekuma:
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    container_name: uptimeKuma
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/uptimekuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001