version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      -3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    external: true