version: '3.8'

services:
  omada:
    image: mbentley/omada-controller:latest
    restart: unless-stopped
    volumes:
      - omada-data:/opt/tplink/EAPController/data
      - omada-data:/opt/tplink/EAPController/logs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Kentucky/Louisville
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8043
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false

volumes:
  omada-data:
    external: true