version: '3.8'

services:
  terraria_vanilla:
    container_name: ${SERVER_NAME}
    image: kaysond/docker-terraria
    stdin_open: true
    tty: true
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      -7777:7777
    volumes:
      - ~/config/app_config/terraria/${SERVER_NAME}/world:world
      - ~/config/app_config/terraria/${SERVER_NAME}/config:config