version: '3.8'

services:
  kavita:
    image: kizaing/kavita:latest
    volumes:
        - kavita-data:/kavita/config
        - ~/kavita:/manga
    ports:
      - 5050:5000
    restart: unless-stopped

volumes:
    kavita-data:
        external: true