services:
  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    volumes:
      - /home_theater_data:/data
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/kavita:/kavita/config
    ports:
      - 5050:5000
    restart: unless-stopped
